/**
 * Created by Administrator on 2016/7/5.
 */
export const INIT_TITLE = 'INIT_TITLE';
export const SET_USER_CARD = 'SET_USER_CARD';
export const USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL = 'USER_SIGN_FAIL';
export const GET_USER_ACHIEVEMENT = 'GET_USER_ACHIEVEMENT';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const GET_ERROR_QUESTIONS_SUCCESS = 'GET_ERROR_QUESTIONS_SUCCESS';
export const GET_ERROR_QUESTIONS_FAIL = 'GET_ERROR_QUESTIONS_FAIL';
export const REMOVE_QST_FAIL = 'REMOVE_QST_FAIL';
export const REMOVE_QST_SUCCESS = 'REMOVE_QST_SUCCESS';